
#define SANITY_TYPE_FEAR	"fear"
#define SANITY_TYPE_DEATH	"death"
#define SANITY_TYPE_DRUGS	"drugs"
#define SANITY_TYPE_CULT	"cult"
#define SANITY_TYPE_UNKNOWN	"unknown"

#define SANITY_SLEEP_RESTORE	1.0
#define SANITY_SAFE_SPACE_RESTORE	0.5
#define SANITY_COMFORT_RESTORE	0.2

#define SANITY_DEATH_LOSS	0.1
#define SANITY_DEATH_LOSS	0.2
#define SANITY_CLONE_LOSS	1.0
#define SANITY_CULT_LOSS	0.2
#define SANITY_UNKNOWN_LOSS	5.0

#define SANITY_UPDATE_RATE	5
